Traceback (most recent call last):
  File "../stat.py", line 67, in <module>
    main()
  File "../stat.py", line 56, in main
    G=get_conductance(filename)
  File "../stat.py", line 21, in get_conductance
    dv= (df["V"].iloc[j]-df["V"].iloc[i])
UnboundLocalError: local variable 'df' referenced before assignment
"../stat.gp", line 7: warning: Skipping data file with no valid points

p "stat.dat" u 1:2 w boxes fs solid 0.5 t ""
                                            ^
"../stat.gp", line 7: x range is invalid

Traceback (most recent call last):
  File "../stat.py", line 67, in <module>
    main()
  File "../stat.py", line 56, in main
    G=get_conductance(filename)
  File "../stat.py", line 21, in get_conductance
    dv= (df["V"].iloc[j]-df["V"].iloc[i])
UnboundLocalError: local variable 'df' referenced before assignment
"../stat.gp", line 7: warning: Skipping data file with no valid points

p "stat.dat" u 1:2 w boxes fs solid 0.5 t ""
                                            ^
"../stat.gp", line 7: x range is invalid

../stat.py:43: RuntimeWarning: invalid value encountered in log10
  stat[i]=(np.absolute((np.log10(G)).astype(int)) == i).sum()
../stat.py:44: RuntimeWarning: invalid value encountered in log10
  stat_rel[i]=(np.absolute((np.log10(G)).astype(int)) == i).sum()/n*100
Traceback (most recent call last):
  File "../stat.py", line 67, in <module>
    main()
  File "../stat.py", line 56, in main
    G=get_conductance(filename)
  File "../stat.py", line 21, in get_conductance
    dv= (df["V"].iloc[j]-df["V"].iloc[i])
UnboundLocalError: local variable 'df' referenced before assignment
"../stat.gp", line 7: warning: Skipping data file with no valid points

p "stat.dat" u 1:2 w boxes fs solid 0.5 t ""
                                            ^
"../stat.gp", line 7: x range is invalid

../stat.py:43: RuntimeWarning: invalid value encountered in log10
  stat[i]=(np.absolute((np.log10(G)).astype(int)) == i).sum()
../stat.py:44: RuntimeWarning: invalid value encountered in log10
  stat_rel[i]=(np.absolute((np.log10(G)).astype(int)) == i).sum()/n*100
../stat.py:43: RuntimeWarning: invalid value encountered in log10
  stat[i]=(np.absolute((np.log10(G)).astype(int)) == i).sum()
../stat.py:44: RuntimeWarning: invalid value encountered in log10
  stat_rel[i]=(np.absolute((np.log10(G)).astype(int)) == i).sum()/n*100
../stat.py:43: RuntimeWarning: invalid value encountered in log10
  stat[i]=(np.absolute((np.log10(G)).astype(int)) == i).sum()
../stat.py:44: RuntimeWarning: invalid value encountered in log10
  stat_rel[i]=(np.absolute((np.log10(G)).astype(int)) == i).sum()/n*100
